# Generated by Django 4.2.1 on 2023-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
