# Generated by Django 4.2.1 on 2023-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0003_alter_tool_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
