# Generated by Django 4.2.1 on 2023-05-25 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0006_tool_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.OneToOneField(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="webtool.rating",
            ),
        ),
    ]
