# Generated by Django 4.2.1 on 2023-07-04 10:50

import ckeditor.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0009_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contents", ckeditor.fields.RichTextField()),
                ("name", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="tool",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/images/"),
        ),
    ]
