# Generated by Django 4.2.1 on 2023-07-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0010_post_alter_tool_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
