# Generated by Django 4.2.1 on 2023-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webtool", "0011_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="license",
            field=models.CharField(
                choices=[("Open Source", "Open Source"), ("Commercial", "Commercial")],
                max_length=100,
            ),
        ),
    ]
