# Generated by Django 4.2.1 on 2023-10-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="media/images/"
            ),
        ),
    ]
